---

- name: Intall updates and packages on Zabbix-Server
  hosts: zabbix
  become: yes

  tasks:
          - name: ping.... is my Server responsible?
            ping:

          - name: update packages
            dnf:
                name: sos
                enablerepo: 'epel, ol7_latest'
                update_cache: yes
           
          - name: remirepo for php
            dnf:
                name: http://rpms.remirepo.net/enterprise/remi-release-8.rpm
                state: present 

          - name: update system
            dnf: name='*' state=latest


          - name: install software on the Server
            dnf:
               name: ['htop', 'mc', 'wget', 'vim', 'dnf-utils', 'net-tools', 'bind-utils', 'network-scripts', 'chrony'] 
               state: latest 

          - name: disable SElinux on the Server
            selinux: state=disabled

            #- name: stop SElinux
            #command: setenforce 0

          - name: enable chrony daemon on the Server
            service: name=chronyd enabled=yes

          - name: chrony daemon start on the Server
            service: name=chronyd state=started 

          - name: copy chrony config file on the Server
            copy: src=/home/doo/chrony.conf dest=/etc/ owner=root group=root mode='0644'   
           
          - name: stop firewalld on the Server
            service: name=firewalld state=stopped enabled=false

          - name: install nginx rpm from remote repo on the Server
            dnf:
                name: http://nginx.org/packages/centos/8/x86_64/RPMS/nginx-1.16.1-1.el8.ngx.x86_64.rpm
                state: present

                #   - name: start & enable nginx on the Server
                #$ service: name=nginx state=started enabled=yes


          - name: install php74 and extentions on the Server
            dnf:
                name: ['php74', 'php-fpm', 'php-cli', 'php-gd', 'php-ldap', 'php-odbc', 'php-pdo', 'php-pear', 'php-xml', 'php-xmlrpc', 'php-mbstring', 'php-snmp', 'php-soap', 'php-bcmath']
                state: latest

          - name: start & enable php-fpm on the Server
            service: name=php-fpm state=started enabled=yes

          - name: copy config file for php-fpm on the Server
            copy: src=/home/doo/www.conf dest=/etc/php-fpm.d/ owner=root group=root mode='0644'

          - name: restart php-fpm on the Server
            service: name=php-fpm state=restarted


          - name: install mariadb on the Server
            dnf:
                name: ['mariadb-server', 'mariadb-gssapi-server']
                state: latest


          - name: start & enable mariadb on the Server
            service: name=mariadb state=started enabled=yes


          - name: copy config file for mariadb to the Server
            copy: src=/home/doo/mariadb-server.cnf dest=/etc/my.cnf.d/ owner=root group=root mode='0644'  


          - name: restart mariadb service on the Server
            service: name=mariadb state=restarted


          - name: upload zabbix 
            dnf:
                name: https://repo.zabbix.com/zabbix/4.4/rhel/8/x86_64/zabbix-release-4.4-1.el8.noarch.rpm
                state: latest

          - name: install zabbix-server
            dnf:
                name: ['zabbix-server-mysql', 'zabbix-web-mysql']
                state: latest

          - name: copy zabbix-server config
            copy: src=/home/doo/zabbix_server.conf dest=/etc/zabbix/ owner=root group=root mode='0644'

          - name: start & enable zabbix-server
            service: name=zabbix-server state=started enabled=yes

          - name: copy config for php-fpm use nginx
            copy: src=/home/doo/zabbix.conf dest=/etc/php-fpm.d/ owner=root group=root mode='0644'

          - name: restart php-fpm using nginx
            service: name=php-fpm state=restarted

          - name: copy nginx config
            copy: src=/home/doo/default.conf dest=/etc/nginx/conf.d/  owner=root group=root mode='0644'


          - name: change permissions to the dir session to nginx:nginx
            file: dest=/var/lib/php/session/ state=directory recurse=yes owner=nginx group=nginx

          - name: change permission on the dir web fo nginx:nginx  
            file: dest=/etc/zabbix/web/ state=directory recurse=yes owner=nginx group=nginx

          - name: restart nginx
            service: name=nginx state=restarted

          


         # create root .my.cnf config file
         # - name: Add .my.cnf
         #   template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

        # Set root password
        # UPDATE mysql.user SET Password=PASSWORD('mysecret') WHERE User='root';
        # FLUSH PRIVILEGES;

            # - name: Set root Password
            # mysql_user: login_password={{ mysql_root_password }} check_implicit_admin=yes name=root host={{ item }} password={{ mysql_root_password }} state=present
            #with_items:
            #   - localhost
            #    - 127.0.0.1
            #    - ::1






            #- name: reboot system
            #command: shutdown -r now
 


