---
# handlers file for zabbix-server

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: restart mariadb
  service: name=mariadb state=restarted

#- name: restart php-fpm using nginx
#  service: name=php-fpm state=restarted

- name: restart nginx
  service: name=nginx state=restarted
