---
- name: update servers and install base prog's
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: check the viability of servers
      ping:

    - name: update system
      apt:
        update_cache: yes

    - name: upgrade system
      apt:
        name: "*"
        state: latest

    - name: full upgrade system
      apt:
        upgrade: dist

    - name: remove pedendencies no required
      apt:
        autoremove: yes
